[package]
name = "scd-osk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
blit = { git = "https://github.com/nicoburniske/blit", rev = "0e10cf45a3da20ef0cc266e30fe0218651aaef1d" }
blit-cpu = { git = "https://github.com/nicoburniske/blit", rev = "0e10cf45a3da20ef0cc266e30fe0218651aaef1d" }
clap.workspace = true
env_logger.workspace = true
evdev.workspace = true
log.workspace = true
scd.workspace = true
serde.workspace = true
smithay-client-toolkit = { version = "0.21.1", default-features = false, features = ["calloop"] }
toml.workspace = true
